# nodejs.yml
---

- name: Add Chris Lea's Repo
  sudo: yes
  apt_repository: repo='ppa:chris-lea/node.js' update_cache=yes

- name: Install nodejs
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - nodejs

